### ISSUE TITLE
怎么用

### ISSUE THREAD

**Issue by luckyboysmith** [Ahaochan/wnacg#1]
你好，请问这怎么用啊，手机安装不了啊

**Comment by Ahaochan** [comment]
已经放弃维护了，有兴趣可以自行编译打包

**Comment by luckyboysmith** [comment]
@Ahaochan  好吧，还是感谢大佬，大佬是wnacg管理员么，现在网站不能下载，可有破解之法，总之，感谢

**Comment by Ahaochan** [comment]
我只是个普通用户，已转战E站

**Comment by luckyboysmith** [comment]
@Ahaochan  总之，还是感谢
